// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7UgTXOpbA_FfX_gT0VX_BUt-neKET_PQ',
    appId: '1:778671566177:web:a314999998538e48096920',
    messagingSenderId: '778671566177',
    projectId: 'gastos-f2292',
    authDomain: 'gastos-f2292.firebaseapp.com',
    storageBucket: 'gastos-f2292.firebasestorage.app',
    measurementId: 'G-K4QVLPR18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiWVSzBf5N1u51wy-wdyBrA0K7eGa-T9c',
    appId: '1:778671566177:android:0d5f320c12069876096920',
    messagingSenderId: '778671566177',
    projectId: 'gastos-f2292',
    storageBucket: 'gastos-f2292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTE7kaMBWk1CzaBbOEl5bk2kBlq1L3uY',
    appId: '1:778671566177:ios:ee7a7ea97b783b84096920',
    messagingSenderId: '778671566177',
    projectId: 'gastos-f2292',
    storageBucket: 'gastos-f2292.firebasestorage.app',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTE7kaMBWk1CzaBbOEl5bk2kBlq1L3uY',
    appId: '1:778671566177:ios:ee7a7ea97b783b84096920',
    messagingSenderId: '778671566177',
    projectId: 'gastos-f2292',
    storageBucket: 'gastos-f2292.firebasestorage.app',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7UgTXOpbA_FfX_gT0VX_BUt-neKET_PQ',
    appId: '1:778671566177:web:1687ac386a52bc7c096920',
    messagingSenderId: '778671566177',
    projectId: 'gastos-f2292',
    authDomain: 'gastos-f2292.firebaseapp.com',
    storageBucket: 'gastos-f2292.firebasestorage.app',
    measurementId: 'G-1M1C8JN66Y',
  );
}
